wfc: Fix checks for reply.
The well-formedness check for <reply> has been rewritten, and for each
reported wfc error a dedicated test has been added. One overlapping test
has been removed.

Some error messages have been improved, so some baselines had been
updated.

The spec for the well-formedness check is as follows:

wfc (o <reply>)
  0. wfc the reply expression
     [[ TODO: wf_expression: general test for expressions]]
  1. reply-with-port
    1.1 if port def not found:
          ERROR "undefined port `p'"
          [[wf_replyPort]]
    1.2 port is a requires port:
          ERROR: "requires port `p' not allowed in reply"
          [[wf_replyRequiresPort]]
    1.3 reply in <on> clause: (reply-in-on o)
    1.4 reply in <function>: (wfc-reply-expression o port)
  2. reply-without-port
    2.1 in interface OR no more than 1 provides port:
      2.1.1 reply in <on> clause: (reply-in-on o)
      2.1.2 reply in <function>: (wfc-reply-expression o #f)
    2.2 in component AND more than 1 provides port:
      2.2.1 if not in <on> clause:
              ERROR: "must specify a provides-port with reply"
              [[wf_replyFunctionMultiplePort]]
      2.2.2 if there is are any out triggers in the <on> clause:
              ERROR: "must specify a provides-port with out-event: `r1.e1', `r2.e2'"
              [[wf_replyOnOutEventMultiplePort]]
      2.2.3 otherwise: (reply-in-on o)

reply-in-on (o <reply>)
  for each of the triggers t in the <on> clause:
    reply-in-on o t

reply-in-on (o <reply>) (t <trigger>)
  'unblocking' means: the model is blocking, and the trigger has a requires port.
  1. reply has a port which is not equal to the trigger port, AND the model is not blocking:
       ERROR: "port `p' does not match with trigger port `q'"
       [[wf_replyOnPort]]
  2. not unblocking AND the trigger event is an in-event:
    2.1 if the event type and the reply type do not match:
          ERROR: "type mismatch: expected `bool', found `int'"
          [[wf_OnType]]
    2.2 otherwise: OK
  3. the model is NOT blocking, and the trigger event is an out-event:
       ERROR: "reply not allowed on out event `e'"
       [[wf_replyOnOutEvent]]
  4. otherwise: (wfc-reply-expression o port)

wfc-reply-expression (o <reply>) port ;; port is a <port> or #f
  1. reply has an expression: check WF expression
  2. if no errors found:
       collect all event return types:
         if a port is given, restrict to that port, otherwise look in all ports.
         ;; FIXME: look in all PROVIDES ports in stead
       2.1. the reply expression's type (or <void>) doen not occur in all event return types:
          2.1.1. port is given:
                   ERROR: "type mismatch: no event with reply type `int' for port `p'"
                   [[wf_blockingReply]]
          2.1.2. no port:
                   ERROR: "type mismatch: no event with reply type `int'"
                   [[wf_replyFunctionExpression]]
       2.2. otherwise: OK

* gaiag/wfc.scm (reply-with-port, reply-without-port, wfc-reply-expression,
reply-in-on): New procedures.
(wfc)[<reply>]: Use them and rewite.
* test/all/wf_replyRequiredPort: Delete test.
* test/all/wf_blockingReply,
test/all/wf_replyTypeMismatch,
test/all/wf_typeerror: Update baseline.
* test/all/wf_replyFunctionExpression,
test/all/wf_replyFunctionMultiplePort,
test/all/wf_replyOnOutEvent,
test/all/wf_replyOnOutEventMultiplePort,
test/all/wf_replyOnPort,
test/all/wf_replyOnType,
test/all/wf_replyPort,
test/all/wf_replyRequiresPort: New tests ....
* test/parser: Add as symbolic link in the parser directory.
* test/all/local.mk (PARSER TESTS): ... and add here.