test: Add alpha_local2.
This test generates broken c++ code:

    test/all/alpha_local2/out/c++/alpha_local2.cc: In member function ‘bool alpha_local2::h_hello()’:
    test/all/alpha_local2/out/c++/alpha_local2.cc:28:26: error: ‘bx’ was not declared in this scope
       this->reply_bool = bx;
                          ^~
* test/all/alpha_local2/alpha_local2.dzn: New test.
* test/all/local.mk (REGRESSION_TESTS): Add it.
(XFAIL_TESTS): Add it.